# Generated by Django 5.1.5 on 2025-02-03 09:07

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_galeri', models.CharField(blank=True, max_length=200, null=True)),
                ('gambar_galeri', models.ImageField(null=True, upload_to='gambar')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('token_galeri', models.CharField(blank=True, max_length=300, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Data Galeri',
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=200, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('banner_satu', models.ImageField(null=True, upload_to='gambar/banner')),
                ('banner_dua', models.ImageField(null=True, upload_to='gambar/banner')),
                ('token_kategori', models.CharField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Data Kategori',
            },
        ),
        migrations.CreateModel(
            name='Kontak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kontak', models.CharField(max_length=200, null=True)),
                ('isi_kontak', models.TextField(blank=True, null=True)),
                ('teks_dua', models.TextField(blank=True, null=True)),
                ('gambar_kontak', models.ImageField(null=True, upload_to='gambar')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('token_kontak', models.CharField(blank=True, max_length=300, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Data Kontak',
            },
        ),
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_layanan', models.CharField(blank=True, max_length=200, null=True)),
                ('isi_layanan', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('gambar_layanan', models.ImageField(null=True, upload_to='gambar')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('token_layanan', models.CharField(blank=True, max_length=300, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Data Layanan',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_profil', models.CharField(max_length=200, null=True)),
                ('teks_satu', models.CharField(max_length=200, null=True)),
                ('keterangan', ckeditor.fields.RichTextField(blank=True, max_length=600, null=True)),
                ('gambar_profil', models.ImageField(null=True, upload_to='gambar', verbose_name='Gambar (1920 x 1200 pixel)')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Data Profil',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=200, null=True)),
                ('teks_awal', ckeditor.fields.RichTextField(blank=True, max_length=200, null=True)),
                ('teks_dua', ckeditor.fields.RichTextField(blank=True, max_length=200, null=True)),
                ('gambar_slide', models.ImageField(null=True, upload_to='gambar/slide')),
                ('aktif', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Data Slide',
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_awal', models.CharField(blank=True, max_length=200, null=True)),
                ('teks_dua', models.CharField(blank=True, max_length=200, null=True)),
                ('alamat', models.CharField(blank=True, max_length=200, null=True)),
                ('gambar_icon', models.ImageField(null=True, upload_to='gambar/icon')),
                ('aktif', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Data Study',
            },
        ),
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_berita', models.CharField(blank=True, max_length=300, null=True)),
                ('gambar_berita', models.ImageField(null=True, upload_to='gambar/berita')),
                ('isi_berita', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('deskripsi_berita', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('token_berita', models.CharField(blank=True, max_length=300, null=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produks', to='administrator.kategori')),
            ],
            options={
                'verbose_name_plural': 'Data Berita',
            },
        ),
    ]
