# Generated by Django 5.1.5 on 2025-02-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='token_slide',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='teks_dua',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
