# Generated by Django 5.1.5 on 2025-02-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_slide_token_slide_alter_slide_teks_dua'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='tanggal_upload',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
