# Generated by Django 5.1.5 on 2025-02-05 14:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_slide_tanggal_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlidePenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_slidepenjualan', models.CharField(blank=True, max_length=200, null=True)),
                ('teks_awal', ckeditor.fields.RichTextField(blank=True, max_length=200, null=True)),
                ('teks_dua', models.CharField(blank=True, max_length=200, null=True)),
                ('gambar', models.ImageField(null=True, upload_to='gambar/slide')),
                ('aktif', models.BooleanField(default=True)),
                ('token_slidepenjualan', models.CharField(blank=True, max_length=300, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Data SlidePenjualan',
            },
        ),
    ]
