# Generated by Django 5.1.5 on 2025-02-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_pemesanan_delete_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemesanan',
            name='nama_pemesanan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
