# Generated by Django 5.1.5 on 2025-02-06 02:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_alter_pemesanan_nama_pemesanan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdukPopuler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_produkpopuler', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_produkpopuler', models.CharField(blank=True, max_length=200, null=True)),
                ('isi_produkpopuler', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('link_produkpopuler', models.CharField(max_length=200, null=True)),
                ('gambar_layanan', models.ImageField(null=True, upload_to='gambar')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('token_pemesanan', models.CharField(blank=True, max_length=300, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Data Pemesanan',
            },
        ),
    ]
