# Generated by Django 5.1.5 on 2025-02-06 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_produkpopuler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkpopuler',
            old_name='gambar_layanan',
            new_name='gambar_produkpopuler',
        ),
    ]
