# Generated by Django 5.1.5 on 2025-02-06 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_rename_gambar_layanan_produkpopuler_gambar_produkpopuler'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produkpopuler',
            options={'verbose_name_plural': 'Data Produk Populer'},
        ),
        migrations.RenameField(
            model_name='produkpopuler',
            old_name='token_pemesanan',
            new_name='token_produkpopuler',
        ),
    ]
