# Generated by Django 5.1.5 on 2025-02-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_alter_produkpopuler_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkpopuler',
            name='link_produkpopuler',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
