# Generated by Django 5.1.5 on 2025-02-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_alter_produkpopuler_link_produkpopuler'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(blank=True, max_length=200, null=True)),
                ('deskripsi_kategori', models.TextField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('token_kategori', models.CharField(blank=True, max_length=300, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Data Kategori Penjualan',
            },
        ),
    ]
