# Generated by Django 5.1.5 on 2025-02-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_kategoripenjualan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategoripenjualan',
            old_name='deskripsi_kategori',
            new_name='deskripsi_kategoripenjualan',
        ),
        migrations.RenameField(
            model_name='kategoripenjualan',
            old_name='nama_kategori',
            new_name='nama_kategoripenjualan',
        ),
        migrations.RenameField(
            model_name='kategoripenjualan',
            old_name='token_kategori',
            new_name='token_kategoripenjualan',
        ),
    ]
