# Generated by Django 5.1.5 on 2025-02-06 09:02

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_rename_deskripsi_kategori_kategoripenjualan_deskripsi_kategoripenjualan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(blank=True, max_length=300, null=True)),
                ('deskripsi_produk', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('harga_produk', models.CharField(blank=True, max_length=300, null=True)),
                ('gambar_produk', models.ImageField(null=True, upload_to='gambar')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('token_berita', models.CharField(blank=True, max_length=300, null=True)),
                ('kategoripenjualan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produks', to='administrator.kategoripenjualan')),
            ],
            options={
                'verbose_name_plural': 'Data Produk',
            },
        ),
    ]
