# Generated by Django 5.1.5 on 2025-02-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_produk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produk',
            old_name='token_berita',
            new_name='token_produk',
        ),
    ]
