# Generated by Django 5.1.5 on 2025-02-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_rename_token_berita_produk_token_produk'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
    ]
