# Generated by Django 5.1.5 on 2025-02-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_produk_aktif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_baground', models.CharField(blank=True, max_length=200, null=True)),
                ('gambar_baground', models.ImageField(null=True, upload_to='gambar/baground')),
                ('aktif', models.BooleanField(default=True)),
                ('token_baground', models.CharField(blank=True, max_length=300, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Data Baground',
            },
        ),
    ]
