# Generated by Django 5.1.5 on 2025-02-10 03:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_baground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baground',
            name='nama_baground',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True),
        ),
    ]
