# Generated by Django 5.1.5 on 2025-02-10 04:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_alter_baground_nama_baground'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiMisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_visimisi', models.CharField(blank=True, max_length=200, null=True)),
                ('isi_visimisi', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('gambar_visimisi', models.ImageField(null=True, upload_to='gambar/visimisi')),
                ('aktif', models.BooleanField(default=True)),
                ('token_visimisi', models.CharField(blank=True, max_length=300, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Data VisiMisi',
            },
        ),
    ]
