# Generated by Django 5.1.5 on 2025-02-12 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_visimisi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produk',
            name='kategoripenjualan',
        ),
        migrations.DeleteModel(
            name='Pemesanan',
        ),
        migrations.DeleteModel(
            name='ProdukPopuler',
        ),
        migrations.DeleteModel(
            name='SlidePenjualan',
        ),
        migrations.DeleteModel(
            name='KategoriPenjualan',
        ),
        migrations.DeleteModel(
            name='Produk',
        ),
    ]
