# Generated by Django 5.1.5 on 2025-02-20 03:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0021_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInkubasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=200, null=True)),
                ('gambar', models.ImageField(null=True, upload_to='gambar')),
                ('deskripsi', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('token_team', models.CharField(blank=True, max_length=300, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Data Model Inkubasi',
            },
        ),
        migrations.AlterField(
            model_name='pekerjaan',
            name='isi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
