# Generated by Django 5.1.5 on 2025-02-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0022_modelinkubasi_alter_pekerjaan_isi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelinkubasi',
            old_name='token_team',
            new_name='token_modelinkubasi',
        ),
        migrations.AlterField(
            model_name='modelinkubasi',
            name='deskripsi',
            field=models.ImageField(null=True, upload_to='gambar'),
        ),
    ]
