# Generated by Django 5.1.5 on 2025-03-23 08:24

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0024_alter_modelinkubasi_deskripsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(null=True, upload_to='gambar')),
                ('nama', models.CharField(blank=True, max_length=200, null=True)),
                ('jabatan', models.CharField(blank=True, max_length=200, null=True)),
                ('deskripsi', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('token_testimoni', models.CharField(blank=True, max_length=300, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Data Testimoni',
            },
        ),
        migrations.AlterModelOptions(
            name='berita',
            options={'ordering': ['-tanggal_upload'], 'verbose_name_plural': 'Data Berita'},
        ),
        migrations.RemoveField(
            model_name='berita',
            name='deskripsi_berita',
        ),
        migrations.RemoveField(
            model_name='berita',
            name='gambar_berita',
        ),
        migrations.RemoveField(
            model_name='berita',
            name='judul_berita',
        ),
        migrations.RemoveField(
            model_name='berita',
            name='token_berita',
        ),
        migrations.AddField(
            model_name='berita',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='berita',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='gambar/berita/'),
        ),
        migrations.AddField(
            model_name='berita',
            name='judul',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='berita',
            name='isi_berita',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='berita',
            name='kategori',
            field=models.CharField(default='Umum', max_length=100),
        ),
        migrations.AlterField(
            model_name='berita',
            name='tanggal_upload',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
