# Generated by Django 5.1.5 on 2025-03-29 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0025_testimoni_alter_berita_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.kategori'),
        ),
    ]
