# Generated by Django 5.1.5 on 2025-03-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0026_alter_berita_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
