# Generated by Django 5.1.5 on 2025-03-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0027_berita_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='berita',
            old_name='token',
            new_name='token_berita',
        ),
    ]
