# Generated by Django 5.1.5 on 2025-03-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0028_rename_token_berita_token_berita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='isi_berita',
            field=models.TextField(blank=True, null=True),
        ),
    ]
