# Generated by Django 5.1.5 on 2025-04-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0029_alter_berita_isi_berita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='deskripsi',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
