# Generated by Django 5.1.5 on 2025-04-02 18:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0030_alter_berita_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='deskripsi',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True),
        ),
    ]
