# Generated by Django 5.1.5 on 2025-04-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0031_alter_berita_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='teitter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
