# Generated by Django 5.1.5 on 2025-04-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0033_rename_teitter_team_twiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='twiter',
        ),
        migrations.AddField(
            model_name='team',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
