# Generated by Django 5.1.5 on 2025-04-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0034_remove_team_twiter_team_twitter_alter_team_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='deskripsi',
        ),
    ]
