# Generated by Django 5.1.5 on 2025-04-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0035_remove_team_deskripsi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='keterangan',
            new_name='deskripsi',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='gambar_profil',
            new_name='gambar',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='nama_profil',
            new_name='judul',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='teks_satu',
        ),
        migrations.AddField(
            model_name='profil',
            name='gambar_2',
            field=models.ImageField(null=True, upload_to='gambar', verbose_name='Gambar (1920 x 1200 pixel)'),
        ),
    ]
