# Generated by Django 5.1.5 on 2025-04-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0036_rename_keterangan_profil_deskripsi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='token_profil',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
