# Generated by Django 5.1.5 on 2025-04-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0037_profil_token_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pesan', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('token_pesan', models.CharField(blank=True, max_length=300, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Pesan',
                'verbose_name_plural': 'Pesan',
            },
        ),
        migrations.AlterModelOptions(
            name='kontak',
            options={'verbose_name_plural': 'Informasi Kontak'},
        ),
        migrations.RemoveField(
            model_name='kontak',
            name='aktif',
        ),
        migrations.RemoveField(
            model_name='kontak',
            name='gambar_kontak',
        ),
        migrations.RemoveField(
            model_name='kontak',
            name='isi_kontak',
        ),
        migrations.RemoveField(
            model_name='kontak',
            name='nama_kontak',
        ),
        migrations.RemoveField(
            model_name='kontak',
            name='teks_dua',
        ),
        migrations.AddField(
            model_name='kontak',
            name='alamat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kontak',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='kontak',
            name='hari',
            field=models.CharField(default='Senin - Jumat', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kontak',
            name='jam',
            field=models.CharField(default='08:00 - 17:00', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kontak',
            name='no_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kontak',
            name='no_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
