# Generated by Django 5.1.5 on 2025-04-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0038_pesan_alter_kontak_options_remove_kontak_aktif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontak',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pesan',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
    ]
