# Generated by Django 5.1.5 on 2025-04-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0039_kontak_aktif_pesan_aktif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visimisi',
            old_name='judul_visimisi',
            new_name='misi',
        ),
        migrations.RenameField(
            model_name='visimisi',
            old_name='isi_visimisi',
            new_name='visi',
        ),
        migrations.RemoveField(
            model_name='visimisi',
            name='gambar_visimisi',
        ),
        migrations.AddField(
            model_name='visimisi',
            name='sasaran',
            field=models.BooleanField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='visimisi',
            name='tujuan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
