# Generated by Django 5.1.5 on 2025-04-20 19:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0040_rename_judul_visimisi_visimisi_misi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategori',
            name='banner_dua',
        ),
        migrations.RemoveField(
            model_name='kategori',
            name='banner_satu',
        ),
        migrations.RemoveField(
            model_name='kategori',
            name='deskripsi',
        ),
        migrations.AlterField(
            model_name='visimisi',
            name='misi',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visimisi',
            name='sasaran',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visimisi',
            name='tujuan',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visimisi',
            name='visi',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True),
        ),
    ]
