# Generated by Django 5.1.5 on 2025-04-30 04:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0042_komentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesan',
            name='tampil_di_website',
            field=models.BooleanField(default=False, verbose_name='Tampilkan di Website'),
        ),
        migrations.AlterField(
            model_name='berita',
            name='deskripsi',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
