# Generated by Django 5.1.5 on 2025-04-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0043_pesan_tampil_di_website_alter_berita_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='tampil_di_website',
            field=models.BooleanField(default=False, verbose_name='Tampilkan di Website'),
        ),
    ]
