# Generated by Django 5.1.5 on 2025-04-30 15:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0044_komentar_tampil_di_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanya', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('jawab', models.CharField(blank=True, max_length=200, null=True)),
                ('noslug', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('token_faq', models.CharField(blank=True, max_length=300, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Data Faq',
            },
        ),
        migrations.AlterField(
            model_name='slide',
            name='teks_awal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
