# Generated by Django 5.1.5 on 2025-05-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0045_faq_alter_slide_teks_awal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='jawab',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='tanya',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
