# Generated by Django 5.1.5 on 2025-05-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0047_daftartenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('alamat', models.EmailField(blank=True, max_length=254, null=True)),
                ('telepon', models.EmailField(blank=True, max_length=254, null=True)),
                ('jenislayanan', models.TextField(blank=True, null=True)),
                ('jenisproduk', models.TextField(blank=True, null=True)),
                ('waktu', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('token_daftartenant', models.CharField(blank=True, max_length=300, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('aktif', models.BooleanField(default=True)),
                ('tampil_di_website', models.BooleanField(default=False, verbose_name='Tampilkan di Website')),
            ],
            options={
                'verbose_name': 'Layanan',
                'verbose_name_plural': 'Layanan',
            },
        ),
    ]
