# Generated by Django 5.1.5 on 2025-05-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0048_daftarlayanan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daftartenant',
            options={},
        ),
        migrations.RemoveField(
            model_name='daftartenant',
            name='tampil_di_website',
        ),
        migrations.AlterField(
            model_name='daftartenant',
            name='jenisusaha',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='daftartenant',
            name='namausaha',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='daftartenant',
            name='telepon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
