# Generated by Django 5.1.5 on 2025-05-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0049_alter_daftartenant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daftarlayanan',
            options={},
        ),
        migrations.RenameField(
            model_name='daftarlayanan',
            old_name='token_daftartenant',
            new_name='token_daftarlayanan',
        ),
        migrations.RemoveField(
            model_name='daftarlayanan',
            name='tampil_di_website',
        ),
        migrations.AddField(
            model_name='daftarlayanan',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
