# Generated by Django 5.1.5 on 2025-05-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0050_alter_daftarlayanan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sejarah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, null=True)),
                ('isi', models.CharField(max_length=200, null=True)),
                ('detail', models.CharField(max_length=200, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('token_sejarah', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'Data Sejarah',
            },
        ),
    ]
