# Generated by Django 5.1.5 on 2025-05-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0051_sejarah'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daftarlayanan',
            options={'verbose_name': 'Daftar Layanan', 'verbose_name_plural': 'Daftar Layanan'},
        ),
        migrations.AddField(
            model_name='daftarlayanan',
            name='pesan',
            field=models.TextField(blank=True, null=True, verbose_name='Pesan'),
        ),
        migrations.AlterField(
            model_name='daftarlayanan',
            name='aktif',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='daftarlayanan',
            name='alamat',
            field=models.TextField(blank=True, null=True, verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='daftarlayanan',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='daftarlayanan',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Sudah Dibaca'),
        ),
        migrations.AlterField(
            model_name='daftarlayanan',
            name='jenislayanan',
            field=models.CharField(blank=True, choices=[('konsultasi', 'Konsultasi'), ('pemasangan', 'Pemasangan'), ('perbaikan', 'Perbaikan'), ('lainnya', 'Lainnya')], max_length=20, null=True, verbose_name='Jenis Layanan'),
        ),
        migrations.AlterField(
            model_name='daftarlayanan',
            name='jenisproduk',
            field=models.CharField(blank=True, choices=[('produk_a', 'Produk A'), ('produk_b', 'Produk B'), ('produk_c', 'Produk C'), ('lainnya', 'Lainnya')], max_length=20, null=True, verbose_name='Jenis Produk'),
        ),
        migrations.AlterField(
            model_name='daftarlayanan',
            name='nama',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Lengkap'),
        ),
        migrations.AlterField(
            model_name='daftarlayanan',
            name='tanggal_upload',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Tanggal Permintaan'),
        ),
        migrations.AlterField(
            model_name='daftarlayanan',
            name='telepon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor Telepon'),
        ),
        migrations.AlterField(
            model_name='daftarlayanan',
            name='token_daftarlayanan',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='daftarlayanan',
            name='waktu',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Layanan'),
        ),
    ]
