# Generated by Django 5.1.5 on 2025-05-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0052_alter_daftarlayanan_options_daftarlayanan_pesan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layanan',
            old_name='isi_layanan',
            new_name='isi',
        ),
        migrations.RenameField(
            model_name='layanan',
            old_name='nama_layanan',
            new_name='nama',
        ),
        migrations.RemoveField(
            model_name='layanan',
            name='aktif',
        ),
        migrations.RemoveField(
            model_name='layanan',
            name='gambar_layanan',
        ),
    ]
