# Generated by Django 5.1.5 on 2025-06-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0055_menupilihan_seleksi_tenantinkubator_adminpaneluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='gambar_1',
            field=models.ImageField(blank=True, null=True, upload_to='gambar/berita/'),
        ),
        migrations.AddField(
            model_name='berita',
            name='gambar_2',
            field=models.ImageField(blank=True, null=True, upload_to='gambar/berita/'),
        ),
        migrations.AddField(
            model_name='berita',
            name='gambar_3',
            field=models.ImageField(blank=True, null=True, upload_to='gambar/berita/'),
        ),
    ]
