# Generated by Django 5.1.5 on 2025-07-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0056_berita_gambar_1_berita_gambar_2_berita_gambar_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='tanggal_upload',
            field=models.DateTimeField(blank=True, help_text='Pilih tanggal berita. Jika dikosongkan, akan otomatis sesuai waktu upload.', null=True),
        ),
    ]
