# Generated by Django 5.1.5 on 2025-08-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0057_alter_berita_tanggal_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='tanggal',
            field=models.DateField(blank=True, help_text='Tanggal berita yang ditentukan oleh user.', null=True),
        ),
    ]
