# Generated by Django 5.1.5 on 2025-08-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0058_berita_tanggal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Galeri',
        ),
        migrations.DeleteModel(
            name='Komentar',
        ),
        migrations.DeleteModel(
            name='Pekerjaan',
        ),
        migrations.AlterField(
            model_name='daftarlayanan',
            name='waktu',
            field=models.DateField(blank=True, help_text='Waktu layanan.', null=True),
        ),
    ]
