# Generated by Django 5.1.5 on 2025-08-22 15:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0059_delete_galeri_delete_komentar_delete_pekerjaan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftartenant',
            name='deskripsi',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
