# Generated by Django 5.1.5 on 2025-08-26 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0060_daftartenant_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftarlayanan',
            name='tanggal',
            field=models.DateField(default=datetime.date.today, verbose_name='Tanggal Layanan'),
        ),
        migrations.AlterField(
            model_name='daftarlayanan',
            name='waktu',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Waktu Layanan'),
        ),
    ]
