# Generated by Django 5.1.4 on 2025-09-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0061_daftarlayanan_tanggal_alter_daftarlayanan_waktu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daftartenant',
            options={'verbose_name': 'Daftar Tenant', 'verbose_name_plural': 'Daftar Tenant'},
        ),
        migrations.AddField(
            model_name='daftartenant',
            name='form_upload',
            field=models.FileField(blank=True, null=True, upload_to='forms/tenant/', verbose_name='Upload Form'),
        ),
    ]
