# Generated by Django 5.1.4 on 2025-09-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0062_alter_daftartenant_options_daftartenant_form_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftarlayanan',
            name='kode_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kode Status'),
        ),
        migrations.AddField(
            model_name='daftarlayanan',
            name='status_email_kode',
            field=models.CharField(choices=[('belum_kirim', 'Belum Kirim'), ('terkirim', 'Terkirim'), ('email_invalid', 'Email Tidak Valid'), ('gagal', 'Gagal Kirim')], default='belum_kirim', max_length=20, verbose_name='Status Email Kode'),
        ),
    ]
