# Generated by Django 5.1.4 on 2025-09-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0063_daftarlayanan_kode_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daftarlayanan',
            name='status_email_kode',
        ),
        migrations.AddField(
            model_name='daftarlayanan',
            name='status_email_token',
            field=models.CharField(choices=[('belum_kirim', 'Belum Kirim'), ('terkirim', 'Terkirim'), ('email_invalid', 'Email Tidak Valid'), ('gagal', 'Gagal Kirim')], default='belum_kirim', max_length=20, verbose_name='Status Email Token'),
        ),
    ]
