# Generated by Django 5.1.5 on 2025-09-29 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0064_remove_daftarlayanan_status_email_kode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(null=True, upload_to='gambar', verbose_name='Gambar (1920 x 1200 pixel)')),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='administrator.profil')),
            ],
            options={
                'verbose_name': 'Gambar Profil',
                'verbose_name_plural': 'Gambar Profil',
                'ordering': ['urutan', 'id'],
            },
        ),
    ]
