# Generated by Django 5.1.5 on 2025-09-29 07:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0065_profilimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='deskripsi',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
    ]
