# Generated by Django 5.1.5 on 2025-10-06 08:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0066_alter_profil_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='video',
            field=models.FileField(blank=True, help_text='Opsional. Unggah video pendukung (mp4/avi/mov).', null=True, upload_to='video/berita/'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='deskripsi',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
