# Generated by Django 5.1.4 on 2025-10-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0067_berita_video_alter_profil_deskripsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, help_text='Nama pemilik/tujuan (opsional)', max_length=150, null=True)),
                ('bot_token', models.CharField(help_text='Bot Token dari @BotFather', max_length=200)),
                ('chat_id', models.CharField(help_text='Chat ID atau Channel ID (mis. -100xxxxxxxxxx)', max_length=100)),
                ('aktif', models.BooleanField(default=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Penerima Telegram',
                'verbose_name_plural': 'Penerima Telegram',
                'ordering': ['-dibuat', '-id'],
            },
        ),
    ]
