# Generated by Django 5.1.5 on 2025-10-13 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0068_telegramrecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftarlayanan',
            name='jenislayanan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.layanan', verbose_name='Jenis Layanan'),
        ),
    ]
