# Generated by Django 5.1.5 on 2025-10-14 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0069_alter_daftarlayanan_jenislayanan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.PositiveIntegerField(default=0)),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('ACCESS', 'Akses'), ('CREATE', 'Buat'), ('UPDATE', 'Ubah'), ('DELETE', 'Hapus'), ('OTHER', 'Lainnya')], default='ACCESS', max_length=10)),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('request_data', models.TextField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_aktivitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Aktivitas',
                'verbose_name_plural': 'Log Aktivitas',
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['-started_at'], name='administrat_started_e04318_idx'), models.Index(fields=['user', 'started_at'], name='administrat_user_id_e94410_idx'), models.Index(fields=['action_type', 'started_at'], name='administrat_action__a37004_idx')],
            },
        ),
    ]
