# Generated by Django 5.1.5 on 2025-11-29 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0071_alter_baground_nama_baground_alter_berita_deskripsi_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faq',
        ),
    ]
