# Generated by Django 5.2.7 on 2025-12-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0073_adminrole_adminpaneluser_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminrole',
            options={'ordering': ['name'], 'verbose_name': 'Role Admin', 'verbose_name_plural': 'Role Admin'},
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_manage_berita',
            field=models.BooleanField(default=False, verbose_name='Kelola Berita'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_manage_faq',
            field=models.BooleanField(default=False, verbose_name='Kelola FAQ'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_manage_galeri',
            field=models.BooleanField(default=False, verbose_name='Kelola Galeri'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_manage_inkubasi',
            field=models.BooleanField(default=False, verbose_name='Kelola Inkubasi'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_manage_kontak',
            field=models.BooleanField(default=False, verbose_name='Kelola Kontak'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_manage_layanan',
            field=models.BooleanField(default=False, verbose_name='Kelola Layanan'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_manage_pendaftaran',
            field=models.BooleanField(default=False, verbose_name='Kelola Pendaftaran'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_manage_pengaturan',
            field=models.BooleanField(default=False, verbose_name='Kelola Pengaturan'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_manage_pengguna',
            field=models.BooleanField(default=False, verbose_name='Kelola Pengguna'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_manage_profil',
            field=models.BooleanField(default=False, verbose_name='Kelola Profil'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_manage_role',
            field=models.BooleanField(default=False, verbose_name='Kelola Role'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_manage_slider',
            field=models.BooleanField(default=False, verbose_name='Kelola Slider'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_manage_team',
            field=models.BooleanField(default=False, verbose_name='Kelola Tim'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_manage_tenant',
            field=models.BooleanField(default=False, verbose_name='Kelola Tenant'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_manage_testimoni',
            field=models.BooleanField(default=False, verbose_name='Kelola Testimoni'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_view_dashboard',
            field=models.BooleanField(default=False, verbose_name='Lihat Dashboard'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_view_logs',
            field=models.BooleanField(default=False, verbose_name='Lihat Log Aktivitas'),
        ),
        migrations.AlterField(
            model_name='adminrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Izin standar Django (opsional)', to='auth.permission', verbose_name='Izin Standar'),
        ),
    ]
