# Generated by Django 5.2.7 on 2025-12-02 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0074_alter_adminrole_options_adminrole_can_manage_berita_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminrole',
            options={'ordering': ['name'], 'verbose_name': 'Admin Role', 'verbose_name_plural': 'Admin Roles'},
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='can_manage_berita',
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='can_manage_faq',
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='can_manage_galeri',
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='can_manage_inkubasi',
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='can_manage_kontak',
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='can_manage_layanan',
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='can_manage_pendaftaran',
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='can_manage_pengaturan',
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='can_manage_pengguna',
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='can_manage_profil',
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='can_manage_role',
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='can_manage_slider',
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='can_manage_team',
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='can_manage_tenant',
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='can_manage_testimoni',
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='can_view_dashboard',
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='can_view_logs',
        ),
        migrations.AlterField(
            model_name='adminrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Pilih izin untuk role ini', to='auth.permission', verbose_name='Izin'),
        ),
        migrations.CreateModel(
            name='AdminUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_roles', to='administrator.adminrole')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin User Role',
                'verbose_name_plural': 'Admin User Roles',
                'ordering': ['-updated_at'],
            },
        ),
    ]
