# Generated by Django 5.1.5 on 2025-12-04 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0075_alter_adminrole_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUserRole',
        ),
    ]
