# Generated by Django 5.1.5 on 2025-12-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0076_delete_adminuserrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpaneluser',
            name='foto_profil',
            field=models.ImageField(blank=True, help_text='Unggah foto profil admin', null=True, upload_to='gambar/admin/', verbose_name='Foto Profil'),
        ),
    ]
