# Generated by Django 5.1.5 on 2025-12-18 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0077_adminpaneluser_foto_profil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuPilihan',
        ),
        migrations.DeleteModel(
            name='Sejarah',
        ),
        migrations.RemoveField(
            model_name='daftarlayanan',
            name='jenisproduk',
        ),
    ]
