# Generated by Django 5.1.5 on 2025-12-18 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0078_delete_menupilihan_delete_sejarah_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpaneluser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Dibuat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminpaneluser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
    ]
