# Generated by Django 5.1.5 on 2025-12-24 03:00

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0079_adminpaneluser_created_at_adminpaneluser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=300, verbose_name='Judul Kegiatan')),
                ('deskripsi', models.TextField(verbose_name='Deskripsi Singkat')),
                ('konten', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Konten Lengkap')),
                ('tanggal_mulai', models.DateTimeField(verbose_name='Tanggal & Waktu Mulai')),
                ('tanggal_selesai', models.DateTimeField(verbose_name='Tanggal & Waktu Selesai')),
                ('tempat', models.CharField(max_length=200, verbose_name='Tempat Kegiatan')),
                ('jenis_kegiatan', models.CharField(choices=[('internal', 'Kegiatan Internal'), ('eksternal', 'Kegiatan Eksternal'), ('pelatihan', 'Pelatihan'), ('seminar', 'Seminar'), ('workshop', 'Workshop'), ('lainnya', 'Lainnya')], default='internal', max_length=20, verbose_name='Jenis Kegiatan')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20, verbose_name='Status')),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='gambar/agenda/', verbose_name='Gambar Poster')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
                ('kontak_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kontak Person')),
                ('email_kontak', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Kontak')),
                ('telepon_kontak', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telepon Kontak')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agenda',
                'ordering': ['-tanggal_mulai'],
            },
        ),
        migrations.RemoveField(
            model_name='adminpaneluser',
            name='created_at',
        ),
    ]
