"""
Django settings for aplikasi project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from decouple import config
from pathlib import Path
import os
import pymysql
import dj_database_url
pymysql.install_as_MySQLdb()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o7790i2&@9=1b64e1t1+q9)cha82la-zq%ij8z()jt6jf%ex(h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DJANGO_DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',
    'administrator',
    'website',
    'cart',
    'django_ckeditor_5'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'website.middleware.SecurityHeadersMiddleware',
    'administrator.middleware.ActivityLogMiddleware',
    'website.middleware.FriendlyErrorMiddleware',
    'administrator.middleware.AdminRoleMiddleware',
    'administrator.middleware.ActivityLogMiddleware',
]

ROOT_URLCONF = 'aplikasi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'administrator.context_processors.notifications',
                'administrator.context_processors.admin_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'aplikasi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Database: hanya MySQL sebagai default
# DATABASES = {
#     'default': dj_database_url.config(
#         default='mysql://localhost:3306/inbis_unuja',
#         conn_max_age=600,
#         ssl_require=False
#     )
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# -------------------------
# Security: Only active in production
# -------------------------
if not DEBUG:
    # Railway sudah handle HTTPS, jadi tidak perlu redirect lagi
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = False  # PENTING: Set False untuk Railway
    
    # HSTS settings
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Cookies over HTTPS only
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Extra protections
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'
    X_FRAME_OPTIONS = 'DENY'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Ini adalah folder tujuan collectstatic

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')  # Tambahkan ini

# Authentication redirects
LOGIN_URL = '/login/'

# Telegram credentials (read from environment variables)
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_CHAT_ID = os.environ.get('TELEGRAM_CHAT_ID', '')

# reCAPTCHA keys (optional; when set, login will require CAPTCHA)
RECAPTCHA_SITE_KEY = config('RECAPTCHA_SITE_KEY', default='')
RECAPTCHA_SECRET_KEY = config('RECAPTCHA_SECRET_KEY', default='')

# Ensure Django appends slash for missing trailing slashes
APPEND_SLASH = True

CKEDITOR_UPLOAD_PATH = 'uploads/ckeditor/' 
CKEDITOR_5_UPLOAD_PATH = "uploads/ckeditor/"
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'undo','redo','|','heading','|','bold','italic','underline','strikethrough','|',
            'link','bulletedList','numberedList','blockQuote','|','insertTable','imageUpload'
        ],
        'height': 300,
        'width': 'auto',
        'language': 'en'
    }
}

# Email Configuration dengan SSL bypass untuk mengatasi certificate error
import ssl
from django.core.mail.backends.smtp import EmailBackend

class SSLBypassEmailBackend(EmailBackend):
    def open(self):
        if self.connection:
            return False
        connection_params = {
            'host': self.host,
            'port': self.port,
            'timeout': self.timeout,
        }
        try:
            import smtplib
            self.connection = smtplib.SMTP(**connection_params)
            if self.use_tls:
                # Buat SSL context yang bypass certificate verification
                context = ssl.create_default_context()
                context.check_hostname = False
                context.verify_mode = ssl.CERT_NONE
                self.connection.starttls(context=context)
            if self.username and self.password:
                self.connection.login(self.username, self.password)
            return True
        except Exception:
            if not self.fail_silently:
                raise

# Email: nonaktifkan pengiriman via SMTP dan gunakan console backend (dev-only)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# SMTP settings dinonaktifkan:
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False
# EMAIL_HOST_USER = ''
# EMAIL_HOST_PASSWORD = ''
# EMAIL_TIMEOUT = 60

# DEFAULT_FROM_EMAIL = 'noreply@example.com'

# Authentication redirects
LOGIN_URL = '/login/'
