# Generated by Django 5.1.5 on 2025-02-12 03:17

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategoripenjualan', models.CharField(blank=True, max_length=200, null=True)),
                ('deskripsi_kategoripenjualan', models.TextField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('token_kategoripenjualan', models.CharField(blank=True, max_length=300, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Data Kategori Penjualan',
            },
        ),
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_pemesanan', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_pemesanan', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('token_pemesanan', models.CharField(blank=True, max_length=300, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Data Pemesanan',
            },
        ),
        migrations.CreateModel(
            name='ProdukPopuler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_produkpopuler', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_produkpopuler', models.CharField(blank=True, max_length=200, null=True)),
                ('isi_produkpopuler', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('link_produkpopuler', models.CharField(blank=True, max_length=200, null=True)),
                ('gambar_produkpopuler', models.ImageField(null=True, upload_to='gambar')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('token_produkpopuler', models.CharField(blank=True, max_length=300, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Data Produk Populer',
            },
        ),
        migrations.CreateModel(
            name='SlidePenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_slidepenjualan', models.CharField(blank=True, max_length=200, null=True)),
                ('teks_awal', ckeditor.fields.RichTextField(blank=True, max_length=200, null=True)),
                ('teks_dua', models.CharField(blank=True, max_length=200, null=True)),
                ('gambar', models.ImageField(null=True, upload_to='gambar/slide')),
                ('aktif', models.BooleanField(default=True)),
                ('token_slidepenjualan', models.CharField(blank=True, max_length=300, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Data SlidePenjualan',
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(blank=True, max_length=300, null=True)),
                ('deskripsi_produk', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('harga_produk', models.CharField(blank=True, max_length=300, null=True)),
                ('gambar_produk', models.ImageField(null=True, upload_to='gambar')),
                ('aktif', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('token_produk', models.CharField(blank=True, max_length=300, null=True)),
                ('kategoripenjualan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produks', to='cart.kategoripenjualan')),
            ],
            options={
                'verbose_name_plural': 'Data Produk',
            },
        ),
    ]
