# Generated by Django 5.1.5 on 2025-05-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_kategoripenjualan_pemesanan_produkpopuler_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slidepenjualan',
            old_name='nama_slidepenjualan',
            new_name='deskripsi',
        ),
        migrations.RenameField(
            model_name='slidepenjualan',
            old_name='gambar',
            new_name='gambar',
        ),
        migrations.RenameField(
            model_name='slidepenjualan',
            old_name='teks_awal',
            new_name='judul',
        ),
        migrations.RenameField(
            model_name='slidepenjualan',
            old_name='teks_dua',
            new_name='nama',
        ),
    ]
