# Generated by Django 5.1.5 on 2025-05-08 15:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_nama_slidepenjualan_slidepenjualan_deskripsi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugkata', models.CharField(blank=True, max_length=200, null=True)),
                ('deskripsi', models.CharField(blank=True, max_length=200, null=True)),
                ('gambar', models.ImageField(null=True, upload_to='gambar')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('token', models.CharField(blank=True, max_length=300, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Data Jasa',
            },
        ),
        migrations.DeleteModel(
            name='ProdukPopuler',
        ),
        migrations.RemoveField(
            model_name='slidepenjualan',
            name='nama',
        ),
        migrations.AlterField(
            model_name='slidepenjualan',
            name='deskripsi',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='slidepenjualan',
            name='judul',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
