# Generated by Django 5.1.5 on 2025-05-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_jasa_delete_produkpopuler_remove_slidepenjualan_nama_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jasa',
            old_name='token',
            new_name='token_jasa',
        ),
    ]
