# Generated by Django 5.1.5 on 2025-05-09 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_rename_nama_kategoripenjualan_kategoripenjualan_nama_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produk',
            old_name='deskripsi_produk',
            new_name='deskripsi',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='gambar_produk',
            new_name='gambar',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='harga_produk',
            new_name='harga',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='nama_produk',
            new_name='nama',
        ),
    ]
