# Generated by Django 5.1.5 on 2025-05-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_rename_deskripsi_produk_produk_deskripsi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoripenjualan',
            name='filter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
