# Generated by Django 5.1.5 on 2025-05-28 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_kategoripenjualan_filter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produk',
            options={'ordering': ['-tanggal_upload'], 'verbose_name_plural': 'Data Deskripsi'},
        ),
    ]
