# Generated by Django 5.1.5 on 2025-07-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_produk_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='gambar2',
            field=models.ImageField(blank=True, null=True, upload_to='gambar'),
        ),
        migrations.AddField(
            model_name='produk',
            name='gambar3',
            field=models.ImageField(blank=True, null=True, upload_to='gambar'),
        ),
    ]
