# Generated by Django 5.1.5 on 2025-08-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_produk_gambar2_produk_gambar3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jasa',
            name='slugkata',
        ),
    ]
