# Generated by Django 5.1.5 on 2025-09-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_remove_jasa_slugkata'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoripenjualan',
            name='gambar',
            field=models.ImageField(null=True, upload_to='gambar'),
        ),
    ]
