# Generated by Django 5.1.5 on 2025-09-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_kategoripenjualan_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='gambar4',
            field=models.ImageField(blank=True, null=True, upload_to='gambar'),
        ),
    ]
