# Generated by Django 5.1.4 on 2025-09-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_produk_gambar4'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='stok',
            field=models.PositiveIntegerField(default=0, help_text='Jumlah stok produk'),
        ),
    ]
