# Generated by Django 5.1.5 on 2025-10-13 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_produk_stok'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemesanan',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='nama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='no_telepon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='pilihan',
            field=models.CharField(choices=[('tertarik', 'Tertarik'), ('ingin_membeli', 'Ingin membeli'), ('ingin_bertanya', 'Ingin bertanya')], default='tertarik', max_length=20),
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='produk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pemesanan_set', to='cart.produk'),
        ),
    ]
