# Generated by Django 5.1.5 on 2025-11-29 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_pemesanan_alamat_pemesanan_email_pemesanan_nama_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produk_tenant', to=settings.AUTH_USER_MODEL, verbose_name='Pemilik Produk'),
        ),
    ]
